# mostly taken from https://gitlab.com/tkpapp/GitlabJuliaDemo.jl

image: julia:1.5

stages:
  - test
  - deploy

test-code-job:
  stage: test
  before_script:
    - echo Testing code by default Pkg.test method.
  script:
    - julia --project=@. -e "import Pkg; Pkg.test(; coverage = false)"

pages:
  stage: deploy
  # before_script:
  #   # workaround for https://github.com/JuliaDocs/Documenter.jl/issues/686
  #   - apt-get -qq update; apt-get -y install git
  #   - julia --project=@. -e "import Pkg; Pkg.build()"
  script:
  #  - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
    # need to explicit specify repo of package, as it is unregistered
    - julia --project=docs -e 'using Pkg; Pkg.activate(); Pkg.add(url="https://gitlab.com/stepanzh/cubiceosdatabase.jl"); Pkg.instantiate()'
    - julia --project=docs --color=yes docs/make.jl
    - mv docs/build public # move to the directory picked up by Gitlab pages
  artifacts:
    paths:
      - public
  only:
  - master
