image: julia:1.4                # image comes from Docker hub

stages:
  - test

test-code-job:
  stage: test
  before_script:
    - echo Testing code by default Pkg.test() method.
  script:
    - julia --project=@. -e "import Pkg; Pkg.test(; coverage = false)"
